### ISSUE TITLE
Add RHDH_REGISTRY_PULL_SECRET to env.sh

### ISSUE THREAD

**Issue by gmodzelewski** [redhat-na-ssa/redhat-developer-hub-gitops-bootstrap#2]
In the env.sh you are writing a list of keys. Running the ansible playbook for rhdh checks before installation, if all needed secrets are in place. Unfortunately one secret is missing. A closer look into the secret shows its name:
RHDH_REGISTRY_PULL_SECRET
It should be the dockerconfig json that can be seen in quay.

**Comment by rafaeltuelho** [comment]
good catch!
I will look at this.
