### ISSUE TITLE
setup-rhdh.yml ansible install error because openshift-helm already exists

### ISSUE THREAD

**Issue by alexgroom** [redhat-na-ssa/redhat-developer-hub-gitops-bootstrap#7]
I needed to comment out this segement of the setup-rhdh.yml file because it failed:

`- name: Add Openshift chart repo
  kubernetes.core.helm_repository:
    name: openshift-helm-charts
    repo_url: "https://charts.openshift.io"
`

On my 4.14 RHPD cluster this was already present so my ansible run failed with:

`TASK [Add Openshift chart repo] ***************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Repository already have a repository named openshift-helm-charts"}
`

**Comment by rafaeltuelho** [comment]
duplicates #3
